### ISSUE TITLE
tox-ansible should not dig for scenario among untracked files

### ISSUE THREAD

**Issue by ssbarnea** [ansible/tox-ansible#77]
I recently come to a bug where I realised that scenarios from other repositories which where cloned during testing endup being detected by tox-ansible.

I think that the only safe way to assure we do not dig too much is to rely on `git ls-files` output instead of using globbing.

@greg-hellings What do you think?

**Comment by greg-hellings** [comment]
Hmm, I would rather not depend on a particular development tool to be present, such as git.

I would prefer some sort of path exclusion option in the `tox.ini` [ansible] section. That way you could prune out certain paths like .tox, .cache, etc. Those two would be a reasonable set of defaults, since we know that both would be created by associated tools, but their absence wouldn't depend on a particular tool being present the way `git ls-files` would.

Would that be manageable?

**Comment by greg-hellings** [comment]
Actually, looking through the code, it already supports the option

```ini
[ansible]
ignore_path =
    foo
    bar/baz
```

Obviously if that's not feature-rich enough or needs to be improved we can do it. But that *should* suffice for the needs. As I said, I would rather not rely on `git` at all, and certainly not on tracked files as I will often use tox-ansible to run against a new role that hasn't been added yet.

**Comment by cidrblock** [comment]
This predates the V2 codebase
